name: Convert Shift_JIS to UTF-8 and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install iconv (via GNU libc)
        run: sudo apt-get update && sudo apt-get install -y libc-bin

      - name: Convert HTML files from Shift_JIS to UTF-8
        run: |
          mkdir output
          for file in *.htm*; do
            iconv -f SHIFT_JIS -t UTF-8 "$file" -o "output/$file"
            sed -i 's/Shift_JIS/UTF-8/g' "output/$file"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
